# Computation

**Summary:** Computation underlies research analytics and faculty use whatever resources they can find. Lots of code and data winds up on the laptops of collaborators and students which works against reproducibility, security, and project continuity. 

## Data Management and Computation

Smaller projects can in fact be completed using laptops and desktops though the trend has rapidly moved towards more samples per project thus being able to easily and conveniently compute against multiple data sources is very important. This is a limitation of Emory Box in that the data cannot be directly accessed via APIs (Application Programming Interfaces). It might be more convenient for it to be in Amazon S3 bucket or a folder attached to a compute node, or in a system such as [DNANexus](https://www.dnanexus.com/) or [Seven Bridges](https://www.sevenbridges.com/) both of which are enterprise frameworks for data management, analysis, and computation. These are currently being considered by WCI in support of their ORIEN http://oriencancer.org/#about  project though it is quite possible that HERCULES could benefit from using the license also since it would provide a standard tool for management, analysis, and compute. However, embracing these tools would still involve formal training and orientation to ensure productivity. 

## Cloud vs Local Resources

All of those interviewed are aware of resources such as Amazon or Google but lack the training to reasonably approach these resources directly unless “chaperoned” by someone more knowledgeable or by involving a funded collaborator. A minority of those interviewed express an interest in knowing how to configure cloud resources at a "nuts and bolts" level though most do not see immediate value in that. Although they do understand that being more facile at the UNIX command line and with R and Python can only help them. In the end, faculty are not fixated on a specific architecture or method of computation as long as it is readily available and accessible using standard, documented methods. Many faculty are getting their computational work done "by hook or by crook" so they are open to a standard, well supported setup that  doesn't require them to "jump around" to different resources throughout the project life cycle. 

### Onboarding Cloud Support

On boarding to the Cloud is a problem. The cloud's ability to match the scope of most any research project is indeed a true convenience which, however, requires significant knowledge to fully exploit. Knowing how to responsibly provision storage, "spin up" instances, create databases, and effectively close out projects are important skills. It has been difficult getting a clear message from the institution as to when a service offering would be official and what precisely the support mechanism would provide particularly as it relates to hands on support and assistance with managing cloud-based instances. A soft opening was announced for Fall of 2018 though the service arrival date is now "early 2019". 

Investigators will need assistance and/or proxies to handle the foundational work which would typically involve students although a more official, permanent, and reliable form of support is essential since students and post docs eventually move on. In absence of enthusiastic end-user support, Amazon or Google will likely not be heavily used except by those already knowledgeable and/or funded specifically to the do such work. At this point, investigators have the impression that they are expected to "self-educate" though they would like a base level of support from LITS or Rollins IT upon which more specific forms of research support could be built. 

### Post Project Data Archival 

Research evolves over time and involves input from collaborators (statisticians, analysts, bioinformatics etc.) which means that the data must remain resident on the cloud as the project evolves. This ongoing occupancy involves costs and while someone could move the data off to cheaper storage and then move it back to EBS, this is inconvenient and also interrupts continuity. Being able to maintain data on the Amazon cloud is an interest especially with the attractive life cycle management tools that can push data out to cheaper levels of storage and, in terms of archival data, Amazon Glacier. Additionally, Amazon provides versioning, flexible permission schemes, and tiers for infrequently accessed data though intelligent use of these features will require support from the institution. It is not apparent that LITS is supporting this direction given that the preferred storage platforms are Emory Box and the Isilon storage systems. Putting data in Box is "okay" but 1) it cannot be computed against and 2) if the institution is truly moving towards a cloud-first solution then investigators should be allocated Amazon S3 storage equivalent in size to the free Emory Box offering. 

## Desktop Support for Open Source Analysis Tools

Faculty have expressed concern at the level of IT desktop support they receive which is limited when considering that they need to conduct analyses on their desktops using open source tools. Being able to install and update opensource tools (e.g. R, Python, add-on packages) and receive troubleshooting assistance is a common need although it has been challenging to obtain such help. While faculty (or their proxy) use the Rollins cluster there will always be a need for desktop computation simply to try things out and/or do trial runs of pipelines found in literature. To this end having more liberal policies for installing tools on the desk top is desired. Note that faculty are NOT expecting the IT group to provide research advice or debug programming issues. However, they should be able to troubleshoot basic installation problems and be able to assist in the updating of packages and generally be aware of desktop issues as it relates to research.
